### ISSUE TITLE
Minimize abusive issue comments demo

### ISSUE THREAD

**Issue by mbhartleytest** [mbhartleytest/bad-word-test#2]
This is a demo of the `staff minimize comments` feature.

**Comment by mbhartleytest** [comment]
whoa...slow down while I report you for abuse

**Comment by testy-mbhartley** [comment]
:trollface:
:trollface:
:trollface:
:trollface:
:trollface:
:trollface:
:trollface:
:trollface:
:trollface:

**Comment by mbhartleytest** [comment]
time to lock this down
